# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cb2e05b10e6cf5a17376dfef9917f2c54c2f8089943a095fb4289d746554c1fdedda829aa2801bbd07686bfe58fd9dfc36a43168c1a824d4b6da13e4e30d438

test:
  secret_key_base: 6f00096b2c5147c0735238a833aa4dec518f26787815816c8f90e050609175f4f4f5a703a2f38d212917d5efee52d8abd3f4094344c670bdf812c533e4a1ded5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
